package sdk

const goTemplate = `// Code generated by API Gateway SDK Generator. DO NOT EDIT.
package {{.PackageName}}

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

// Client is the {{.Title}} API client.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Headers    map[string]string
}

// NewClient creates a new API client.
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL:    baseURL,
		HTTPClient: http.DefaultClient,
		Headers:    make(map[string]string),
	}
}

// Response wraps an API response.
type Response struct {
	StatusCode int
	Body       []byte
	Header     http.Header
}

func (c *Client) do(ctx context.Context, method, path string, body interface{}) (*Response, error) {
	var bodyReader io.Reader
	if body != nil {
		data, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal body: %w", err)
		}
		bodyReader = bytes.NewReader(data)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return &Response{
		StatusCode: resp.StatusCode,
		Body:       respBody,
		Header:     resp.Header,
	}, nil
}

{{range .Endpoints}}
// {{FuncName .OperationID}} calls {{.Method}} {{.Path}}.
{{- if .Summary}}
// {{.Summary}}
{{- end}}
func (c *Client) {{FuncName .OperationID}}(ctx context.Context{{range .PathParams}}, {{.Name}} {{GoParamType .Type}}{{end}}{{if .HasBody}}, body interface{}{{end}}{{range .QueryParams}}, {{.Name}} {{GoParamType .Type}}{{end}}) (*Response, error) {
	path := fmt.Sprintf({{SprintfFmt .Path}}{{SprintfArgs .PathParams}})
	{{- if .QueryParams}}
	q := url.Values{}
	{{- range .QueryParams}}
	q.Set("{{.Name}}", fmt.Sprint({{.Name}}))
	{{- end}}
	path += "?" + q.Encode()
	{{- end}}
	return c.do(ctx, "{{.Method}}", path{{if .HasBody}}, body{{else}}, nil{{end}})
}
{{end}}
`
