// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {type: 'doc', id: 'index', label: 'Overview'},
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
